version: '3.1'

services:
  frm-comparison-postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: frm-comparison-db
    ports:
      - "5433:5432"
    volumes:
      - ./world.sql:/docker-entrypoint-initdb.d/world.sql
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
